import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Hermes Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='h-screen flex flex-col bg-slate-600'>
          <div className='w-full flex justify-between items-center h-20 bg-zinc-800 text-white p-5'>
            <p>Hermes Chat</p>
            <div className='flex gap-5'>
              <button>Download</button>
              <button>About</button>
              <button>Support</button>
            </div>
          </div>
      </div>
    </>
  )
}
