import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Layout } from '../layout/layout'

import styles from '../../styles/Form.module.css'
import white_hermes_sandal from '../../public/assets/white_hermes_sandal.png'

export default function login() {
    return (
        <Layout>
            <Head>
                <title>Hermes Chat - Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/hermes_logo.png" />
            </Head>

            <section className='w-3/4 h-full mx-auto flex flex-col justify-around sm:justify-between py-5'>
                {/* Logo */}
                <div className='flex justify-center items-center'>
                    <Image src={white_hermes_sandal} alt='logo' height={50}/>
                    <h1 className='text-white text-2xl'>Hermes Chat</h1>
                </div>
                {/* Title */}
                <div>
                    <h1 className='text-white text-5xl sm:text-3xl'>Welcome Back Traveler</h1>
                    <h2 className='text-[#b5bbb3]'>Ready to Login</h2>
                </div>
                {/* Form */}
                <form className='flex flex-col items-center gap-10'>
                    {/* Info Input */}
                    <div className='w-full sm:w-4/5 flex flex-col gap-5'>
                        <div className={styles.input_group}>
                            <label className='text-white'>Username <span className='text-red-700'>*</span></label>
                            <input className={styles.input_text} type='text' />
                        </div>
                        <div className={styles.input_group}>
                            <label className='text-white'>Password <span className='text-red-700'>*</span></label>
                            <input className={styles.input_text} type='text' />
                        </div>
                    </div>
                    {/* Register Button */}
                    <div className={styles.button}>
                        <button type='submit'>Login</button>
                    </div>
                </form>
                {/* Register */}
                <p className='block text-white'>Don't have an account? <Link href={'/register'} className='text-[#2b78cd] hover:underline'>Register</Link></p>
            </section>

        </Layout>
    ) 
}
 