import React from 'react'
import Head from 'next/head'
import ChatPage from '../../components/ChatPage'

export default function DirectMessages() {
  return (
    <>
        <Head>
            <title>Hermes Chat - rooms</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/hermes_logo.png" />
        </Head>

        <ChatPage page={'rooms'}/>
    </>
  )
}
