import Head from 'next/head'
import { LoginPage } from '../components/LoginPage'

export default function Login() {
  return (
    <>
      <Head>
        <title>Hermes Chat - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/hermes_logo.png" />
      </Head>

      <LoginPage />
      
    </>
  )
}