import Head from 'next/head'
import RegisterPage from '../components/RegisterPage'


export default function Register() {
  return (
    <>
      <Head>
        <title>Hermes Chat - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/hermes_logo.png" />
      </Head>

      <RegisterPage />
      
    </>
  )
}