# Generated by Django 4.1.3 on 2022-11-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_business_slug_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='url',
            new_name='website',
        ),
    ]
